server:
  port: 3000
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/userdb?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: qqqq
    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
management:
  security:
    enabled: false
feign:
  hystrix:
    enabled: true